### ISSUE TITLE
Lacking of modules in no3_generate_montage.py

### ISSUE THREAD

**Issue by DemoAllan** [yyfang678/DMIB#1]
Dear author,
     It is a really nice work and when trying to run the code in no3_generate_montage.py, it seems that there is No module named 'image_processing'. Could you please provide the code of this module?
    Looking forward to your kind reply.

**Comment by yyfang678** [comment]
Hi, thank you for bringing this to my attention. I have uploaded the missing module file ('image_processing.py') to the project repository. Please try running the code again.

**Comment by yyfang678** [comment]
> Dear author, It is a really nice work and when trying to run the code in no3_generate_montage.py, it seems that there is No module named 'image_processing'. Could you please provide the code of this module? Looking forward to your kind reply.

**Comment by yyfang678** [comment]
> Dear author, It is a really nice work and when trying to run the code in no3_generate_montage.py, it seems that there is No module named 'image_processing'. Could you please provide the code of this module? Looking forward to your kind reply.

Hi, thank you for bringing this to my attention. I have uploaded the missing module file ('image_processing.py') to the project repository. Please try running the code again.
